version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.10.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build

workflows:
  main:
    jobs:
      - build
