version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          command: yarn install
          name: Install
      - run:
          command: yarn build
          name: Build

workflows:
  main:
    jobs:
      - build
