version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
        keys:
          - yarn-lock-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          command: yarn install
          name: Install
      - save_cache:
        keys:
          - yarn-lock-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          command: yarn build
          name: Build

workflows:
  main:
    jobs:
      - build
