name: E2E

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node LTS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright browsers
      run: pnpm e2e:setup
    - name: Run Playwright tests
      run: pnpm e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
